world_address = "0x00a71ca11a93851d12746627c16a07f52d3324e8d8d36b04da6c959fd5e932d7"
rpc = "https://api.cartridge.gg/x/starknet/sepolia"

[server]
http_cors_origins = ["*"]

[grpc]
optimistic = true

[indexing]
world_block = 0
controllers = true
pending = true
pre_confirmed = true
polling_interval = 250
contracts = []

[sql]
historical = [
  "NUMS-TrophyProgression",
  "NUMS-QuestProgression",
  "NUMS-BundleIssued",
]

[erc]
metadata_updates = true
